### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by FevLoad** [rafakob/service.pogdesign.sync#3]
I downloaded and installed the plugin 
put the login details 
but nothing happen 
close - reopen the kodi 
refresh the library 
all still the same 

could you please see whats wrong with it ???

**Comment by rafakob** [comment]
Indeed it stopped working. I'm gonna look into it.

**Comment by TomVarga** [comment]
```
17:50:45 T:7000  NOTICE: pogdesign-sync: Library has been changed. Performing full sync.....
17:51:01 T:7000  NOTICE: pogdesign-sync: Full sync has been performed.
```

Worked fine for me just now.

**Comment by FevLoad** [comment]
@calebzor 
Could you please copy past your code here so, i can try it out.

**Comment by TomVarga** [comment]
@Respectme it's same as 0.1.2

**Comment by FevLoad** [comment]
@calebzor
What kodi's version do you use

**Comment by TomVarga** [comment]
@Respectme 19:28:09 T:9772  NOTICE: Starting Kodi (15.2 Git:20151019-02e7013). Platform: Windows NT x86 32-bit

**Comment by FevLoad** [comment]
im using this version on windows 64bit (Windows 7) 
kodi 14.2 git:20150326-7cc53a9

Question : do i need to add the show to http://www.pogdesign.co.uk/cat/
before the add-on can sync them with what i already watched ?

or it just work on its own , add the shows , mark the episodes to watched ?

**Comment by TomVarga** [comment]
Apparently the script was not working for shows with simple one word title. I've created a pull request ( #5 ) that fixes that, that might fix this issue as well,

**Comment by djraw** [comment]
Just yesterday rafakob committed my pull request with updates to URLs mainly. The sync works just fine for me again.
@Respectme : you don't need to add shows in order to succesfully sync, but the addon won't add it to your favs list automatically either as far as I understand the code. So in order to conveniently get info about your watched shows you still need to add them manually to your favs on the website.

I guess this issue can be closed, sorry for reviving a year after. ;)

**Comment by FevLoad** [comment]
Hello there,
I really thank you for your helping but I still get filed to sync and addon broke when I do run it.

> - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
                                            Traceback (most recent call last):
                                              File "C:\Users\ADSL\AppData\Roaming\Kodi\addons\service.pogdesign.sync\service.py", line 108, in <module>
                                                Main()
                                              File "C:\Users\ADSL\AppData\Roaming\Kodi\addons\service.pogdesign.sync\service.py", line 62, in __init__
                                                self.run()
                                              File "C:\Users\ADSL\AppData\Roaming\Kodi\addons\service.pogdesign.sync\service.py", line 103, in run
                                                self.full_sync()
                                              File "C:\Users\ADSL\AppData\Roaming\Kodi\addons\service.pogdesign.sync\service.py", line 77, in full_sync
                                                calendar.login(USERNAME, PASS)  # login to calendar
                                              File "C:\Users\ADSL\AppData\Roaming\Kodi\addons\service.pogdesign.sync\cal.py", line 20, in login
                                                self.submit_form(self.baseURL + '/login', form)
                                              File "C:\Users\ADSL\AppData\Roaming\Kodi\addons\service.pogdesign.sync\cal.py", line 31, in submit_form
                                                urllib2.urlopen(request)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1241, in https_open
                                                context=self._context)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 1198, in do_open
                                                raise URLError(err)
                                            URLError: <urlopen error [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
                                            -->End of Python script error report<--


some help would be appreciated in here.

**Comment by djraw** [comment]
Are you still using Kodi 14.2? That might be the issue as I think it doesn‘t handle SSL very well.
The changes I made to the URLs are mainly because the calendar changed from http to https.

I‘m using SPMC 16.7-04 on 3 Android Boxes and the plugin works on every one of them. The SPMC Kodi fork added fixes to handling SSL. I think you need to update Kodi to make it work or use another fork. You might run into other issues with your setup as most services switched to https.

**Comment by FevLoad** [comment]
I’m using the latest version.

> Kodi v17.6 "Krypton"

and the problem still happening
